---
format:
  html:
    echo: false
    theme: journal
    jupyter: python3    
---

<style>
  @import url('https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Oxygen:wght@300;400;700&family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap');
    
    body {
        background: #F9FCFD;
        color: #51271E;
    }
    
    code[class^=sourceC]{
        font-family: 'Space Mono', monospace;
        /*background-color: #FDFBF9; /*Cambiar dependiendo del fondo que se tenga + el tema de Quarto*/
        font-size: 0.75rem;
    }

    h1 {
        font-weight: 700;
        font-size: 1.8rem;
        font-family: 'Oxygen', sans-serif;
    }

    p {
        font-weight: 400;
        font-size: 0.75rem;
        font-family: 'Noto Serif', serif;
    }

    details>summary {
      font-family: 'Oxygen', sans-serif;
      font-weight: 700;
      font-size: 0.75rem;
      color: #51271E; /*Mismo color que aparece en body (texto)*/
      /*filter: saturate(50%) /*Menor saturación*/
    }



    #title_style {
      font-family: 'Oxygen', sans-serif;
      font-size: 1.1rem;
      font-weight: 700
    }


   #caption {
        font-size: 0.6rem;
        font-weight: 300;
    }
    
    #url_paleta_colores {
        color: steelblue;
        text-decoration: none;
    }

    #nota_subtitle {
        margin-top: -1em;
    }

    /* = = Vega-Lite Charts = = */
    /*
    .vega-embed {
        width: 100%;
        display: flex;
    }

    .vega-embed details,
    .vega-embed details summary {
        position: relative;
    }

    .vega-bind-name {
        font-weight: 400;
        color: #F1EFE3
    } */
    /* - Tooltips - */
    #vg-tooltip-element {
        max-width: 200px;
        font-family: 'Noto Serif', serif; /* Cambiar dependiendo de font-family de <p> */
        color: #51271E;
        font-weight: 400;
        border-radius: 15px;
        background-color: #FDFBF9; /* Cambiar dependiendo del tema + fondo + chart a usar */
    }
</style>

<h1>#30DayMapChallenge Day 22: North is not always up</h1>

<p id="title_style">... except when talking about <em>per capita</em> CO<sub>2</sub> emissions</p>
<p id="nota_subtitle">
Carbon dioxide (CO<sub>2</sub>) emissions from fossil fuels and industry. Land use change is not included.
</p>


```{python}
#| eval: false

```




<p id="caption">
<b>Data</b>: <br></b>Isaac Arroyo (@unisaacarroyov)</b>
</p>