---
format:
  html:
    echo: false
jupyter: python3
---

<style>
    @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Source+Sans+3:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Space+Mono&display=swap');
    
    #quarto-content {
        background: #FAF6E8;
        color: #4F0335;
    }
    
    p code:not(.sourceCode), li code:not(.sourceCode) {
        font-family: 'Space Mono', monospace;
        background-color: #FDFCF6;
        color: #034F1D;
    }

    h1 {
        font-weight: 900;
        font-size: 1.8rem;
        font-family: 'Playfair Display', serif;
    }

    p {
        font-weight: 400;
        font-size: 0.9rem;
        font-family: 'Source Sans 3', sans-serif;
    }
   
   #caption {
        font-size: 0.7rem;
        font-weight: 300;
    }
    
    #url_paleta_colores {
        color: #5C2313;
        text-decoration: none;
    }

    #nota_subtitle {
        font-size: 0.65rem;
        font-style: italic;
        margin-top: -1em;
    }

</style>

<h1>#30DayMapChallenge Day 3: Polygons</h1>

<p>
Simplificación de los límites geográficos de los estados de México (y por ende, de todo el país).</p>
<p id="nota_subtitle">
<b>Nota</b>: Para lograr los polígonos, se usó <code>gdf['geometry'].simplify(tolerance = 0.35, preserve_topology = False)</code>. Los colores son de la paleta <strong>Klein</strong> de la paquetería de <strong>R</strong><code>{MoMAColors}</code> de <strong>Blake Robert Mills</strong> (<em>@BlakeRobMills</em> en Twitter/X)
</p>

```{python load-libraries}
#| eval: false
import numpy as np
import pandas as pd
import geopandas


# = = DATA PROCESSING = = #
# Espacio para mostrar el procesamiento de datos para crear los poligonos 
# con GeoPandas

# - - Cargar el GeoJSON desde GitHub - - #
gdf = geopandas.read_file("https://raw.githubusercontent.com/isaacarroyov/datos_facil_acceso/main/Gobierno-Mexicano/geometrias/00ent_mexico.geojson")

# - - Simplifcar las geometrias - - #
gdf_simplified = gdf.copy()
gdf_simplified['geometry'] = gdf_simplified['geometry'].simplify(tolerance = 0.35, preserve_topology = False)

# - - Guardar para tener en el repositorio y usar directamente con una URL para graficar en Altair - - #
gdf_simplified.to_file("./../data/geom_mexico_polygons.geojson", driver = "GeoJSON")
```

```{python datavis}
import altair as alt
alt.renderers.set_embed_options(actions=False)

# = = LOAD DATA = = #
data_polygons_mexico = alt.Data(url = "https://raw.githubusercontent.com/isaacarroyov/30daymapchallenge/main/data/geom_mexico_polygons.geojson", format = alt.DataFormat(property = "features"))

# = = DATAVIS CONFIG = = #
blake_klein_colour_palette = ["#FF4D6F", "#C86780", "#928191", "#5C9BA2", "#7E9279", "#AA864B", "#D6791C", "#E5890E", "#EEA107", "#F6B801", "#DFBB0B", "#B9B51C", "#94AF2D", "#7EA147", "#708E67", "#637B87", "#627C96", "#6E9092", "#7AA58F", "#809E80", "#7F6D62", "#7E3C44", "#761B32", "#5C1F3D", "#412248", "#36264C", "#682B36", "#9A3020", "#C73710", "#C44C33", "#C06156", "#BD777A"]


# = = LAYERS = = #
poligonos = (alt.Chart(data_polygons_mexico)
                .mark_geoshape(strokeWidth = 0)
                .encode(
                    color = (alt.Color(shorthand = "properties.cve_geo:O")
                                .legend(None)
                                .scale(range = blake_klein_colour_palette))
                )
            )


# = = FINAL DATAVIS = = #
mapa = (poligonos
        .properties(width = "container", height = 500, background = "transparent")
       )

mapa
```


<p id="caption">
<b>Datos</b>: <em>Marco Geoestadístico de México (2022)</em> a través del <b>INEGI</b> (Poligonos oficiales).<br><em>Isaac Arroyo (@unisaacarroyov)</em>
</p>
<br>
<br>