---
format:
  html:
    echo: false
    theme: cosmo
    fig-responsive: true
---

<style>
    @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&family=Libre+Baskerville:wght@700&family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap');
      
    body {
        background: #F1F0E8;
        color: #000000;
    }
    
    code[class^=sourceC]{
        font-family: 'Space Mono', monospace;
        /*background-color: #FDFBF9; /*Cambiar dependiendo del fondo que se tenga + el tema de Quarto*/
        font-size: 0.75rem;
    }

    h1 {
        font-weight: 700;
        font-size: 1.8rem;
        font-family: 'Libre Baskerville', serif;
    }

    p {
        font-weight: 400;
        font-size: 0.75rem;
        font-family: 'Lato', sans-serif
    }

    details>summary {
      font-family: 'Libre Baskerville', serif;
      font-weight: 700;
      font-size: 0.75rem;
      color: #000000; /*Mismo color que aparece en body (texto)*/
      /*filter: saturate(50%) /*Menor saturación*/
    }


    #title_style {
      font-family: 'Libre Baskerville', serif;
      font-size: 1.1rem;
      font-weight: 700
    }


   #caption {
        font-size: 0.6rem;
        font-weight: 300;
    }
    
    #url_paleta_colores {
        color: steelblue;
        text-decoration: none;
    }

    #nota_subtitle {
        margin-top: -1em;
    }

    /* = = Vega-Lite Charts = = */
    /*
    .vega-embed {
        width: 100%;
        display: flex;
    }

    .vega-embed details,
    .vega-embed details summary {
        position: relative;
    }

    .vega-bind-name {
        font-weight: 400;
        color: #F1EFE3
    } */
    /* - Tooltips - */
    #vg-tooltip-element {
        max-width: 200px;
        font-family: 'Lato', sans-serif /* Cambiar dependiendo de font-family de <p> */
        /*color: #51271E; /* Font del cuerpo*/
        font-weight: 400;
        border-radius: 15px;
        /*background-color: #FDFBF9; /* Cambiar dependiendo del tema + fondo + chart a usar */
    }
</style>

<h1>#30DayMapChallenge Day 18: Atmosphere</h1>

<p id="title_style">Vapor de Agua en Latinoamérica (Noviembre 13 - 14, 2023).</p>
<p id="nota_subtitle" style="margin-bottom:-0.2em;">
La personas llegan a creer que el vapor de agua es el principal motivo por el calentamiento actual de la Tierra. Sin embargo, esto es falso, ya que el incremento del vapor de agua <em>no causa</em> el calentamiento del planeta, es una <b>consecuencia</b>. El incremento del vapor de agua <b>amplifica</b> el calentamiento causado por otros gases de efecto invernadero.
</p>

```{r}
#| warning: false
#| fig-asp: 1
library(tidyverse)
library(sf)
library(ggtext)
library(sysfonts)
library(showtext)

font_add_google("Libre Baskerville", "Libre Baskerville")
font_add_google("Lato", "Lato")
showtext_auto()

# setwd("./scripts")

sf_water_vapor_latam <- geojsonsf::geojson_sf("./../data/water_vapor_latam.geojson")
sf_latam <- geojsonsf::geojson_sf("https://raw.githubusercontent.com/isaacarroyov/datos_facil_acceso/main/Mundo/world_shapes_from_altair_website.geojson") %>%
  filter(REGION_WB == 'Latin America & Caribbean')

p1 <- ggplot() +
  geom_sf(data = sf_water_vapor_latam,
          mapping = aes(fill = ordered(zone)),
          linewidth = 0) +
  geom_sf(data = sf_latam,
          fill = "transparent",
          color = "#EEE0C9",
          linewidth = 0.5) +
  scale_fill_manual(values = MetBrewer::met.brewer("Hokusai2", n = 4), labels = paste(c("0 a 15","15 a 30","30 a 45",'Mayor que 45'), "kg&frasl;m<sup>2</sup>")) +
  guides(fill = ggplot2::guide_legend(title = "Cantiad de vapor<br>de agua")
  ) + 
  theme_void() +
  theme(
    legend.position = c(0.2,0.31),
    legend.title = element_markdown(face = "bold",
                                    family = "Libre Baskerville",
                                    size = 30,
                                    lineheight = 0.2,
                                    margin = margin(b = -0.2, unit = "in")),
    legend.text = element_markdown(family = "Lato",
                                   size = 25,
                                   margin = margin(l = -0.15, unit = "in")),
    legend.background = element_rect(fill = "#EEE0C9", color = "transparent"),
    legend.margin = margin(rep(0.1, 4), unit = "in"),
    legend.key = element_blank(),
  )

tgutil::ggpreview(plot = p1, bg = "#F1F0E8")
```

<p id="caption" style="margin-top:-4em;">
Datos: <span style='font-weight:600;'>NCEP/NCAR Reanalysis Project</span> a través de Google Earth Engine.<br>Isaac Arroyo (@unisaacarroyov)
</p>

<details><summary>Earth Engine Python API</summary>

```python
import ee
import geemap
ee.Initialize()

# = = ROI = = #
roi = ee.Geometry.Rectangle([[-123.5, -55.5],[-32.5,32.5 ]])

# = = LOAD DATA = = #
imgColl_waterVapor = ee.ImageCollection('NCEP_RE/surface_wv').filter(ee.Filter.date('2023-11-13', '2023-11-14'))
img_waterVapor = imgColl_waterVapor.select('pr_wtr').mean().clip(roi)

# = = CREATE VECTORS = = #
# - - Categories - - #
category_ranges = img_waterVapor.gt(0).add(img_waterVapor.gt(15)).add(img_waterVapor.gt(30)).add(img_waterVapor.gt(45))
category_ranges = category_ranges.updateMask(category_ranges.neq(0))

fc = category_ranges.addBands(img_waterVapor).reduceToVectors(
    geometry = roi,
    crs = img_waterVapor.projection(),
    scale = 278300,
    geometryType = 'polygon',
    eightConnected = False,
    labelProperty = 'zone',
    reducer = ee.Reducer.mean())

# = = SAVE TO DRIVE = = #
geemap.ee_export_vector_to_drive(
    collection = fc,
    description= "Exportar datos de Vapor de Agua de LATAM",
    fileNamePrefix = "water_vapor_latam",
    fileFormat = "GeoJSON",
    folder = "folder_name")
```

</details>
